# Generated by Django 4.1.5 on 2023-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'pre'), ('Standard', 'std'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
