# Generated by Django 4.1.5 on 2023-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'free'), ('Premium', 'pre'), ('Standard', 'std')], default='Free', max_length=30),
        ),
    ]
