# Generated by Django 4.1.5 on 2023-01-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='slugg',
            new_name='slug',
        ),
    ]
